apiVersion: apps/v1
kind: Deployment
metadata:
  name: glimpse-gan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glimpse-gan
  template:
    metadata:
      labels:
        app: glimpse-gan
    spec:
      containers:
      - name: gan-project-container
        image: gan-project:latest
        ports:
        - containerPort: 80
